export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Gradio"
  | "Ollama"
  | "CodeLlama"
  | "LLaMA2"
  | "Express"
  | "REST API"
  | "Streamlit"
  | "LangChain"
  | "FAISS"
  | "HuggingFace Embeddings"
  | "Groq"
  | "OpenAI"
  | "PyPDF2"
  | "Requests"
  | "JSON"
  | "Stripe"
  | "Twilio"
  | "Razorpay"
  | "Clerk"
  | "Framer Motion";

export type ValidCategory =
  | "AI/ML"
  | "NLP"
  | "Developer Tools"
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  // | "contributions"
  | "resume";
